[workspace]
members = [
    "crates/rpglot-core",
    "crates/rpglot",
    "crates/rpglotd",
    "crates/rpglot-web",
]
resolver = "3"

[workspace.package]
version = "0.2.2"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = "symbols"
panic = "abort"
